# This image contains everything you need for this week's task.
#
# Use this for GitLab CI...
# image: "smblott/dcu-docker-gitlab-ci"
#
# Use this for testing locally (no asciidoc)...
image: smblott/dcu-docker-gitlab-ci

# We'll do everything in one stage, here.
#
test:
   script:
      - make build
      - npm install
      - make run-test-rpn
